//import lab2.ex1.Book;
//import lab2.ex2.*
//import lab3.ex2.*;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String arg[])
	{
		lab3.ex2.UIApplication.run(arg);
		/*final String array[]= {"Basic Java","Advance Java","Forget about Java"};
		Book b= new Book(array);
		System.out.println("The title of Chapter 1 is "+b.getChapter(1));
		String anotherArray[]=b.getChapters();
		
		System.out.println("There are "+anotherArray.length+" chapters.");
		System.out.println(java.util.Arrays.toString(anotherArray));
		
		//New items below 
		Computer a =new MobileComputer();
		for(int i=0;i<10;i++) 
		{
			a.work();
		}
			//New  stuffs again 
			Charger c=new Charger();
			Phone p= new Phone();
			MobileComputer m=new MobileComputer();
			c.charge(p);
			c.charge(m);//This does not work without fixing MobileComputer 
		
		*/
		//System.out.println("NO BLUE RIBBONS");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
